### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by munadikiehl** [jeanbi/Eat-what#2]
Dear Sir/Madam,
Hi, my name is Munadi Kiehl. I'm a graphic designer and I would like to collaborate on your open source project and to propose free icon/logo design. If you're interested in, please, let me know.

Best Regard,
Munadi Kiehl

**Comment by jeanbi** [comment]
Hi Munadi,
Thanks for your attention.
If I have any requirement I'll contact you first, thanks.
But I need to close this issue.

Best regard.
Jimmy

**Comment by munadikiehl** [comment]
Thanks for your feedback @jeanbi.
